# Generated by Django 5.1.3 on 2025-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sale_user_alter_sale_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
