# Generated by Django 5.1.3 on 2025-08-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_last_expiry_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='inventory.supplier'),
        ),
    ]
